#!/usr/bin/env bash

set -euo pipefail

#-------------------------------------------------------------------------------
#
# GCC build script
# Author: Sebastien Alaiwan (inspired by the one made by venix)
# Date: 2016-07-11
#
# The basic steps are:
# 0) Download and extract all the required packages
# 1) build the binutils, ./configure with --target=$(TARGET)
# 2) install the binutils: make install
# 3) build the core-gcc, configure with --target=$(TARGET), make all-gcc
# 4) install the core-gcc: make install-gcc
# 5) build the mingw runtime (libc) using the core-gcc
# 6) finish building gcc: go back to the core-gcc build directory and run "make"
# 7) install gcc: make install
#-------------------------------------------------------------------------------
readonly VENDOR=ace # replace with anything you like
readonly TARGET=i686-${VENDOR}-mingw32
readonly PREFIX=/tmp/toolchains/gcc-$TARGET # the resulting toolchain will land here

readonly SERVER_URL=http://ftp.gnu.org/gnu
readonly GCC_VERSION=5.4.0
readonly BINUTILS_VERSION=2.26
readonly GDC_COMMIT=ad1f2a22dbcbc30f7d12593184e59b607404b25a # (just before the upgrade to 2.68 FE breakage)

readonly GCC_LANGS="c,c++,d"

readonly ARCHIVES=/tmp/archives

readonly scriptDir=$(realpath $(dirname $0))

# Things like CC="ccache gcc" don't play nice with cross builds
unset CC
unset CXX

readonly MAKE="make -j`nproc` -k"
export LDFLAGS=-s

function main
{
  mkdir -p $ARCHIVES
  mkdir -p src bin

  binutils_download
  gcc_download
  gdc_download
  mingw64_download

  lazy binutils_build

  lazy mingw64_extract
  lazy mingw64_install_headers

  lazy gcc_extract
  lazy gdc_apply
  lazy gcc_configure
  lazy gcc_standalone_build
  lazy gcc_standalone_install

  lazy mingw64_build

  lazy gcc_build
  lazy gcc_install

  echo "==============="
  echo "Done"
}

#-------------------------------------------------------------------------------
# BINUTILS
#-------------------------------------------------------------------------------
readonly BINUTILS_SRC=src/binutils
readonly BINUTILS_BIN=bin/binutils

function binutils_download
{
  atomic_wget "$SERVER_URL/binutils/binutils-$BINUTILS_VERSION.tar.bz2" "$ARCHIVES/binutils.tar.bz2"
}

function binutils_build
{
  extract_to "$ARCHIVES/binutils.tar.bz2" $BINUTILS_SRC

  rm -rf "$BINUTILS_BIN"
  mkdir -p "$BINUTILS_BIN"
  readonly DIR=$(realpath $BINUTILS_SRC)
  pushd "$BINUTILS_BIN"
  $DIR/configure \
    --prefix="$PREFIX" \
    --target=$TARGET \
    --disable-nls --with-gcc --with-gnu-as --with-gnu-ld \
    --disable-werror \
    --disable-shared 2>&1 >/dev/null
  popd

  $MAKE -C "$BINUTILS_BIN" CFLAGS="-O2 -fno-exceptions" LDFLAGS="-s"
  $MAKE -C "$BINUTILS_BIN" install
}

#-------------------------------------------------------------------------------
# MINGW 64 (LIBC)
#-------------------------------------------------------------------------------
MINGW64_SRC=src/mingw64
MINGW64_BIN=bin/mingw64

function mingw64_download
{
  atomic_wget "http://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v3.0.0.tar.bz2" "$ARCHIVES/mingw64.tar.bz2"
}

function mingw64_extract
{
  extract_to $ARCHIVES/mingw64.tar.bz2 $MINGW64_SRC
}

function mingw64_install_headers # "sys-include"
{
  rm -rf "bin/mingw64-headers"
  mkdir -p "bin/mingw64-headers"
  local dir=$(realpath $MINGW64_SRC)

  pushd bin/mingw64-headers
  $dir/mingw-w64-headers/configure --host=$TARGET --prefix="$PREFIX/$TARGET"
  popd

  $MAKE -C bin/mingw64-headers
  $MAKE -C bin/mingw64-headers install
}

function mingw64_build
{
  rm -rf "$MINGW64_BIN"
  mkdir -p "$MINGW64_BIN"

  local dir=$(realpath $MINGW64_SRC)

  pushd "$MINGW64_BIN"
  $dir/configure --host=$TARGET --prefix="$PREFIX/$TARGET" PATH="$PREFIX/bin:$PATH"
  popd

  $MAKE -C "$MINGW64_BIN" PATH="$PREFIX/bin:$PATH"
  $MAKE -C "$MINGW64_BIN" install PATH="$PREFIX/bin:$PATH"
}

##-------------------------------------------------------------------------------
## GCC CORE
##-------------------------------------------------------------------------------
readonly GCC_SRC=src/gcc
readonly GCC_BIN=bin/gcc

function gcc_download
{
  atomic_wget "$SERVER_URL/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.bz2" $ARCHIVES/gcc.tar.bz2
}

function gcc_extract
{
  extract_to $ARCHIVES/gcc.tar.bz2 $GCC_SRC

  pushd $GCC_SRC
  ./contrib/download_prerequisites
  popd
}

function gcc_configure
{
  local dir=../../$GCC_SRC # 'dir' must be a relative path, otherwise GMP will not build under Msys2/Cygwin
  mkdir -p "$GCC_BIN"
  pushd $GCC_BIN
  $dir/configure \
    -v \
    --disable-bootstrap \
     --without-headers \
     --enable-targets=all \
     --prefix="$PREFIX" \
     --target="$TARGET" \
     --enable-languages=$GCC_LANGS \
     --with-gcc --with-gnu-ld --with-gnu-as \
     --enable-threads \
     --disable-nls \
     --disable-win32-registry \
     --disable-shared \
     --disable-multilib \
     --enable-sjlj-exceptions \
     --disable-java-awt \
     --without-x \
     --enable-lto
  popd
}

function gcc_standalone_build
{
  $MAKE all-gcc           -C "$GCC_BIN"
  $MAKE all-target-libgcc -C "$GCC_BIN"
}

function gcc_standalone_install
{
  $MAKE -C "$GCC_BIN" install-gcc
}

function gcc_build
{
  $MAKE all -C "$GCC_BIN"
}

function gcc_install
{
  $MAKE install -C "$GCC_BIN"
}

#------------------------------------------------------------------------------
# GDC
#------------------------------------------------------------------------------
function gdc_download
{
  if [ -d src/gdc ] ; then
    echo "Already downloaded: gdc"
    return 0;
  fi
  git clone https://github.com/D-Programming-GDC/GDC.git src/gdc
}

function gdc_apply
{
  patch -p1 --merge -d $GCC_SRC < $scriptDir/patches/gcc/0001-Remove-fPIC-for-MinGW.patch
  pushd src/gdc
  git checkout origin/gdc-5
  git checkout $GDC_COMMIT
  ./setup-gcc.sh ../gcc
  popd
}

#------------------------------------------------------------------------------
# Generic stuff
#------------------------------------------------------------------------------

function atomic_wget
{
  local readonly url=$1
  local readonly output=$2
  if test -f $output ; then
    echo "Already downloaded: $output"
    return 0;
  fi
  mkdir -p $(dirname $output)
  wget "$url" -O $output
}

function extract_to
{
  local file=$1
  local dir=$2

  tar xlf "$file"
  rm -rf "$dir"
  mv "`tar tlf $file 2>/dev/null | head -n 1 | cut -f 1 -d '/'`" "$dir"
}

function lazy
{
  local readonly func="$1"

  mkdir -p flags
  if [ -f flags/$func ] ; then
    return 0
  fi

  echo "$func ..."
  $func & # fork: prevent the callee to change the caller's environment
  pid=$!
  if ! wait $pid ; then
    echo "Failure with: $func"
    return 1
  fi

  touch flags/$func
}

main "$@"

